# Generated by Django 5.1.3 on 2024-11-20 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uni_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
